Feature/modularize
SeatsApp/Backend pull request #48
Opened 2022-05-13 10:40 UTC by tvdw2000

2022-05-16 07:12 UTC, bavodaniels commented on application/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
application shouldnt need starter web

and shouldnt need most of the dependencies below here
(javax, oauth2 client, AD, security)

2022-05-16 07:14 UTC, bavodaniels commented
configureCors in application module should reside in rest adapter module

2022-05-16 07:16 UTC, bavodaniels commented on application/src/test/java/com/seatapp/controllers/LoginControllerTest.java
>  import javax.transaction.Transactional;
tests should be in the module which defines them

2022-05-16 07:18 UTC, bavodaniels commented
core/src/main/java/com/seatapp/domain/usermanagement/JwtUserDetails.java should be in rest module, 
and in the rest module you can block/allow certain calls to the core with the info from the user

and you can pass a POJO user object to the core (without any annotations or only with jpa annotations if that's your choice)

2022-05-18 06:56 UTC, LanderTuyteleersXplore requested changes
The core build.gradle file still contains dependencies to spring-boot-web & spring-boot oath. These should be removed.

2022-05-18 07:41 UTC, bavodaniels approved these changes

2022-05-18 09:32 UTC, LanderTuyteleersXplore approved these changes

2022-05-18 10:01 UTC, merged